// <auto-generated />
namespace Forca.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Migração2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migração2));
        
        string IMigrationMetadata.Id
        {
            get { return "201812261354185_Migração2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
